### ISSUE TITLE
p2p

### ISSUE THREAD

**Issue by AbdelrhmanAmin** [vichuge/5-Design-Teardown#1]
style.css: line-17 : flex-direction: wrap; *FIX THIS*

**Comment by VanessaAoki** [comment]
Hey guys! This is a beautiful project, congratulations.

I do have some suggestions to make (our tse asked us for these changes in our project):

1. For the footer, the list should be displayed in 3 different lines;
2.The same applies to the "footer-options", they should be displayed in 2 lines, don't forget to add the underline;

Keep up the good work
